services:

  pg:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    
  adminer:
    image: adminer
    ports:
      - "8000:8000"
  
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"
